version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
      - "80:5000"
      # - "443:5000" 

    environment:
      - DB_NAME=maze_bank
      - DB_USER=postmalonegres
      - DB_PASSWORD=P0stresostgres4432
      - DB_HOST=db 
      - DB_PORT=5432
    depends_on:
      - db
    volumes:
      - ./static/uploads:/app/static/uploads
    networks:
      - vuln_network

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=maze_bank
      - POSTGRES_USER=postmalonegres
      - POSTGRES_PASSWORD=P0stresostgres4432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vuln_network

volumes:
  postgres_data:

networks:
  vuln_network:
    driver: bridge